site_name: Geist
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - Setup: setup.md
  - Commands:
    - report:
      - Introduction: report/introduction.md
      - Tags: 
        - Tag create: report/tags/tag-create.md
        - Tag destroy: report/tags/tag-destroy.md
        - Tag graph: report/tags/tag-graph.md
        - Tag graph2: report/tags/tag-graph2.md
        - Tag load: report/tags/tag-load.md
        - Tag query: report/tags/tag-query.md
        - Tag component: report/tags/tag-component.md
        - Tag map: report/tags/tag-map.md
        - Tag html: report/tags/tag-html.md
        - Tag img: report/tags/tag-img.md
        - Tag table: report/tags/tag-table.md
        - Tag use: report/tags/tag-use.md
    - create: commands/create.md
    - destroy: commands/destroy.md
    - export: commands/export.md
    - graph: commands/graph.md
    - load: commands/load.md
    - query: commands/query.md
  - Changelog: changelog.md
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
