site_name: Geist
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
  language: en
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
nav:
  - Home: index.md
  - Setup: setup.md
  - Commands:
    - report: commands/report.md
    - create: commands/create.md
    - destroy: commands/destroy.md
    - export: commands/export.md
    - graph: commands/graph.md
    - load: commands/load.md
    - query: commands/query.md
  - Geist templates:
    - What is a Geist template?: templates/what-is-a-geist-template.md
    - Tags: templates/tags.md
    - Filters: templates/filters.md
  - Changelog: changelog.md
markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.details
  - admonition
