        graph LR
	style N1 fill:#b3e2cd, stroke:#333, stroke-width:1px
	style N2 fill:#b3e2cd, stroke:#333, stroke-width:1px
N1(10) --> |× 2| N2(20)
	style N3 fill:#b3e2cd, stroke:#333, stroke-width:1px
N1 --> |× 3| N3(30)
	style N4 fill:#b3e2cd, stroke:#333, stroke-width:1px
	style N5 fill:#b3e2cd, stroke:#333, stroke-width:1px
N4(120) --> |× 2| N5(240)
	style N6 fill:#b3e2cd, stroke:#333, stroke-width:1px
N4 --> |× 3| N6(360)
	style N7 fill:#b3e2cd, stroke:#333, stroke-width:1px
	style N8 fill:#b3e2cd, stroke:#333, stroke-width:1px
N7(135) --> |× 2| N8(270)
	style N9 fill:#b3e2cd, stroke:#333, stroke-width:1px
N7 --> |× 3| N9(405)
	style N10 fill:#b3e2cd, stroke:#333, stroke-width:1px
N10(15) --> |× 2| N3
	style N11 fill:#b3e2cd, stroke:#333, stroke-width:1px
N10 --> |× 3| N11(45)
	style N12 fill:#b3e2cd, stroke:#333, stroke-width:1px
	style N13 fill:#b3e2cd, stroke:#333, stroke-width:1px
N12(160) --> |× 2| N13(320)
	style N14 fill:#b3e2cd, stroke:#333, stroke-width:1px
N12 --> |× 3| N14(480)
	style N15 fill:#b3e2cd, stroke:#333, stroke-width:1px
N15(180) --> |× 2| N6
	style N16 fill:#b3e2cd, stroke:#333, stroke-width:1px
N15 --> |× 3| N16(540)
	style N17 fill:#b3e2cd, stroke:#333, stroke-width:1px
N2 --> |× 2| N17(40)
	style N18 fill:#b3e2cd, stroke:#333, stroke-width:1px
N2 --> |× 3| N18(60)
N5 --> |× 2| N14
	style N19 fill:#b3e2cd, stroke:#333, stroke-width:1px
N5 --> |× 3| N19(720)
N8 --> |× 2| N16
	style N20 fill:#b3e2cd, stroke:#333, stroke-width:1px
N8 --> |× 3| N20(810)
N3 --> |× 2| N18
	style N21 fill:#b3e2cd, stroke:#333, stroke-width:1px
N3 --> |× 3| N21(90)
	style N22 fill:#b3e2cd, stroke:#333, stroke-width:1px
N13 --> |× 2| N22(640)
	style N23 fill:#b3e2cd, stroke:#333, stroke-width:1px
N13 --> |× 3| N23(960)
	style N24 fill:#b3e2cd, stroke:#333, stroke-width:1px
N17 --> |× 2| N24(80)
N17 --> |× 3| N4
N11 --> |× 2| N21
N11 --> |× 3| N7
	style N25 fill:#b3e2cd, stroke:#333, stroke-width:1px
N25(5) --> |× 2| N1
N25 --> |× 3| N10
N18 --> |× 2| N4
N18 --> |× 3| N15
N24 --> |× 2| N12
N24 --> |× 3| N5
N21 --> |× 2| N15
N21 --> |× 3| N8
    